- src/Test.js
- src/Test2.js
- 없습니다
- 없습니다
- src/Test.js
- src/Test2.js
close: #
> test: pr test진행

- public/index.html
- src/App.js
- src/Test.js
- src/Test2.js
- 없음
- public/index.html
- src/App.js
- src/Test.js
- src/Test2.js
- 없음
close: #
> style: prettier 설정 동기화 확인

- public/index.html
- src/Test.js
- src/Test2.js
- src/Test.js
- src/Test2.js
- public/index.html
close: #4
> style: Prettier 테스트 최종

- package-lock.json
- package.json
Co-authored-by: GreattitJY
<great.tit.jaejae@gmail.com>
- 없음
- package-lock.json
- package.json
- 없음
close: #
> setting: react-router-dom 모듈설치

- src/App.js
- src/App.jsx
- src/pages/Chat/Chat.jsx
- src/pages/Home/Home.jsx
- src/pages/Login/Login.jsx
- src/pages/MyProfile/MyProfile.jsx
- src/pages/NotFound/NotFound.jsx
- src/pages/OtherProfile/OtherProfile.jsx
- src/pages/PostCreate/PostCreate.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- src/share/Footer.jsx
- src/share/Header.jsx
- src/share/Post.jsx
- src/share/ProfileSettion.jsx
- src/share/SimpleUserList.jsx
Co-authored-by: GreattitJY
<great.tit.jaejae@gmail.com>
- App.js
- 없음
- src/
close: #7
> chore: 폴더구조 및 라우터 설정

- package-lock.json
- package.json
- postcss.config.js
- src/index.css
- src/index.js
- src/pages/Chat/Chat.jsx
- src/share/Footer.jsx
- tailwind.config.js
- 없음
- 없음
- 
- tailwind.config.js
- src/ (tailwind 설정)
close: #10
> setting: Tailwind 환경 설정

- src/App.jsx
- src/pages/Chat/Chat.jsx
- src/pages/Home/Home.jsx
- src/pages/Login/Login.jsx
- src/pages/MyProfile/MyProfile.jsx
- src/pages/NotFound/NotFound.jsx
- src/pages/OtherProfile/OtherProfile.jsx
- src/pages/PostCreate/PostCreate.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- src/share/Footer.jsx
- src/share/Header.jsx
- src/share/Post.jsx
- src/share/ProfileSettion.jsx
- src/share/SimpleUserList.jsx
- 없음
- src/*.{js,jsx}
- 없음
close: #12
> setting: 함수 포맷 변경

- postcss.config.js
- src/index.css
- src/pages/Chat/Chat.jsx
- src/share/Footer.jsx
- tailwind.config.js
#14 
- 없음
- src/index.css 등 
- 없음
- 
close: #
> design: Tailwind 적용 확인

- src/index.css
> design: 버튼 공통 스타일 설정

- src/index.css
> design: 페이지 레이아웃

- src/share/Footer.jsx
#18 
- 없음
- src/share/Footer.jsx
- 없음
close: #
> design: footer 레이아웃 완성

- src/pages/SplashScreen/SplashScreen.jsx
- 없음
- src/pages/SplashScreen/SplashScreen.jsx
- 없음
close: #31
> feat: Splash Screen 화면 구현

- src/components/LoginBtn/LoginBtn.jsx
- src/pages/Login/Login.jsx
- 없음
- src/pages/Login/Login.jsx
- src/components/LoginBtn/LoginBtn.jsx
close: #
> feat: 로그인버튼 컴포넌트 생성 및 로그인 초기화면 구현

- src/share/SimpleUserList.jsx
design: 유저 리스트 마크업 및 디자인
#33 
- 없음
- src/share/SimpleUserList.jsx
- 없음
close: #
> design: 유저 리스트 마크업 및 디자인

- src/components/LoginBtn/LoginBtn.jsx
- src/pages/Login/Login.jsx
- 없음
- src/components/LoginBtn/LoginBtn.jsx
- src/pages/Login/Login.jsx
- 없음
close: #40
> fix: border 변수읽지 못하는 버그 수정

- src/pages/Home/Home.jsx
- src/share/Post.jsx
- 없음
- src/share/Post.jsx
- 없음
- 나중에 추가 예정
close: # 32
> design: Post 컴포넌트 디자인 작업 및 Home  main 요소 레이아웃 설정

- src/share/Post.jsx
#32
- 없음
- src/share/Post.jsx
- 없음
close: #
> fix: Post 컴포넌트 수정사항 반영 중 발생한 props undefined 오류 해결 작업

- src/share/Footer.jsx
- src/share/HeaderBind.jsx
- 없음
- src/share/Footer.jsx
- src/share/HeaderBind.jsx
close: #44
> fix: header, footer 크기 안줄어들게 수정

- src/pages/Chat/Chat.jsx
- 없음
- src/pages/Chat/Chat.jsx
- 없음
close: #
> design: Chat 페이지 중복 스타일 설정 제거

- src/share/Club.jsx
- 없음
- 없음
- src/share/Club.jsx
close: #49
> design: Club 디자인 및 좌우 스크롤 버튼 기능 구현

- src/share/UserProfile.jsx
#48 
-  없음
- 없음
- src/share/UserProfile.jsx
close: #
> design: 유저 프로필 마크업 및 디자인

- src/share/SimpleUserList.jsx
#33
- 없음
- src/share/SimpleUserList.jsx
- 없음
close: #
> feat: 팔로우 버튼 클릭 시 취소 기능 추가

- src/components/LoginAndJoin/LoginAndJoin.jsx
- src/pages/LoginEmail/LoginEmail.jsx
- src/pages/SignUp/SignUp.jsx
- src/share/ProfileSetting.jsx
- src/share/ProfileSettion.jsx
- 없음
- src/share/ProfileSettion.jsx
- 없음
close: #54
> Feat: 프로필 설정 컴포넌트 생성

- package-lock.json
- package.json
- tailwind.config.js
#50 
- 없음
- package.json
- package-lock.json
- tailwind.config.js
close: #50
> setting: tailwind-scrollbar-hide 모듈 설치

- src/App.jsx
- src/components/LoginBtn/LoginBtn.jsx
- src/index.css
- src/pages/Chat/Chat.jsx
- src/pages/Home/Home.jsx
- src/pages/Login/Login.jsx
- src/pages/MyProfile/MyProfile.jsx
- src/share/Footer.jsx
- src/share/HeaderBind.jsx
- src/share/SimpleUserList.jsx
- 없음
- 모듈 컴포넌트 
- src/App.jsx
- src/pages/
- src/share/
- 없음
close: #62
> chore: 모듈 조립, 컴포넌트 수정

- src/index.css
> refactor: index.css 스타일 수정

- src/components/SimpleClub/SimpleClub.jsx
- src/pages/Chat/Chat.jsx
- src/pages/Home/Home.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- src/share/Club.jsx
- src/share/SimpleUserList.jsx
- src/share/UserProfile.jsx
#75 
- 없음
- src/pages/Chat/Chat.jsx
- 없음
close: #
> refactor: 기본 페이지 레이아웃 및 index.css 수정에 따른 페이지 컴포넌트 스타일 수정

- src/share/HeaderBind.jsx
#65 
- 없음
- src/share/HeaderBind.jsx
- 없음
close: #65
> refactor: HeaderBind.jsx header 스타일 수정

- src/share/Footer.jsx
#69 
- 없음
- src/share/Footer.jsx
- 없음
close: #69
> refactor: Footer.jsx 스타일 수정

- src/pages/NotFound/NotFound.jsx
- 없음
- src/pages/NotFound/NotFound.jsx
- 없음
close: #83
> feat: 404페이지 구현

- src/index.css
- tailwind.config.js
#64 
- 없음
- tailwind.config.js
- 없음
close: #
> setting: tailwind.config.js color 변수화 및 index.css 에 적용

- src/share/Post.jsx
#88
- 없음
- src/share/Post.jsx
- 없음
- 
close: #
> help: 이미지 캐러셀 구현 중 transform 작동 안 함

- src/components/Modal/Modal.jsx
- src/components/ModalInfo/ModalInfo.jsx
- src/pages/MyProfile/MyProfile.jsx
- src/share/HeaderBind.jsx
- 없음
- src/pages/MyProfile/MyProfile.jsx
- src/share/HeaderBind.jsx
- src/components/Modal/Modal.jsx
- src/components/ModalInfo/ModalInfo.jsx
close: #86
> help: 모달창 추가

- src/share/Footer.jsx
#18 
- 없음
- src/share/Footer.jsx
- 없음
close: #
> feat: URL에 따른 footer 이미지 변경

- src/App.jsx
- src/components/ChatModule/ChatRoomFooter/ChatRoomFooter.jsx
- src/components/ChatModule/UserChat/UserChat.jsx
- src/pages/Chat/ChatRoom/ChatRoom.jsx
- 없음
- src/App.jsx
- src/pages/Chat/ChatRoom/ChatRoom.jsx
- src/components/ChatModule/ChatRoomFooter/ChatRoomFooter.jsx
- src/components/ChatModule/UserChat/UserChat.jsx
close: #91
> feat: ChatRoom 라우터 및 컴포넌트 생성

- src/components/Modal/Modal.jsx
- src/components/ModalInfo/ModalInfo.jsx
- 없음
- src/components/Modal/Modal.jsx
- src/components/ModalInfo/ModalInfo.jsx
- 없음
close: #96
> design: 배경색 흰색으로 바꾼후 box-shadow적용

- src/share/ProfileShare/ProfileSetting/ProfileSetting.jsx
- src/share/ProfileShare/UserProfile/UserProfile.jsx
#92 
- 없음
- src/ProfileShare/
-  src/ProfileShare 폴더
- 
close: #
> ProfileShare 폴더 구조 변경

- src/components/Modal/Modal.jsx
- src/components/ModalInfo/ModalInfo.jsx
- src/pages/MyProfile/MyProfile.jsx
- src/share/HeaderBind.jsx
- 없음
- src/components/Modal/Modal.jsx
- src/components/ModalInfo/ModalInfo.jsx
- src/pages/MyProfile/MyProfile.jsx
- src/share/HeaderBind.jsx
- 없음
close: #86
> design: 뒷배경 blur처리 변경, 쓸데없는 코드 삭제

- src/components/ChatModule/UserChat/UserChat.jsx
- src/components/LoginAndJoin/LoginAndJoin.jsx
- src/components/Modal/Modal.jsx
- src/components/ModalInfo/ModalInfo.jsx
- src/components/SimpleClub/SimpleClub.jsx
- src/index.css
- src/pages/Chat/Chat.jsx
- src/pages/Login/Login.jsx
- src/pages/NotFound/NotFound.jsx
- src/share/Footer.jsx
- src/share/HeaderBind.jsx
- src/share/Post.jsx
- src/share/ProfileShare/ProfileSetting/ProfileSetting.jsx
- src/share/ProfileShare/UserProfile/UserProfile.jsx
- src/share/SimpleUserList.jsx
- src/share/UserProfile.jsx
#design: 전반적인 디자인 수정
- 없음
- src/* (모든 파일을 수정한 것은 아니나 거의 모든파일을 수정하여 이와같이 작성합니다.)
- index.css
- 없음
close: #101
> design: 전반적인 디자인 수정

- src/index.css
> fix: text의 rem px로 변경

- src/pages/PostCreate/PostCreate.jsx
#94 
- 없음
- 
- src/pages/PostCreate/PostCreate.jsx
- 없음
- 
close: #
> fix: 하단부의 label 여백 클릭 시 작동 오류 해결

- src/share/Post.jsx
#108
- 없음
- src/share/Post.jsx
- 없음
close: #108
> fix: Post.jsx 106번 머지 충돌 이슈 해결을 위한 누락사항 복원

- src/App.jsx
- 없음
- src/App.jsx
- 없음
close: #114
> fix: App.jsx의 SignUp 파일 경로 수정

- src/App.jsx
- src/pages/ChatList/ChatList.jsx
- src/shared/SimpleUserList/SimpleUserList.jsx
#33 
- App.jsx에서 쓰이지 않는 import 삭제 (Navigate)
- src/pages/ChatList에서 Link 삭제
- 없음
- 
- src/App.jsx
- src/pages/ChatList/ChatList.jsx
- 없음
close: #
> feat: SimpleUserList 디자인 수정 및 클릭 이벤트 활성화(navigate)

- src/App.jsx
- src/api/axios.jsx
- src/components/CheckAuth/CheckAuth.jsx
- src/components/LoginAndSignup/LoginAndSignup.jsx
- src/pages/LoginEmail/LoginEmail.jsx
- src/pages/SignUp/SignUp.jsx
- 없음
- src/
- src/api/axios.jsx
close: #36
> feat: 로그인 api 기능 구현, token 관리, CheakAuth 기능 구현

- package-lock.json
- package.json
- 없음
- package.json
- 없음
close: #117
> setting: axios 모듈 설치

- src/api/axios.jsx
- src/components/Textarea/Textarea.jsx
- src/pages/PostUpload/PostUpload.jsx
- 없음
- src/api/axios.jsx
- src/components/Textarea/Textarea.jsx
- src/pages/PostUpload/PostUpload.jsx
- 없음
close: #94
> Feat/PostUpload 구현 및 axios, textarea  컴포넌트 수정

- src/shared/Header/HeaderSave.jsx
- 없음
- src/shared/Header/HeaderSave.jsx
- 없음
- 
close: #122
> refactor: HeaderSave 컴포넌트 props 수정 (isActive, disabled 속성 추가)

- src/pages/LoginEmail/LoginEmail.jsx
- src/pages/SignUp/SignUp.jsx
#121 
- 없음
- src/pages/LoginEmail/LoginEmail.jsx
- 없음
close: #
> feat: 이메일검증 구현, 입력값에 따라 버튼 비활성화 기능 구현

- src/components/NoFeed/NoFeed.jsx
- src/pages/Home/Home.jsx
- src/shared/Post/Post.jsx
#124
- api 데이터 가져오기, 
- 날짜 정보 처리기능 수정 (updatedAt을 기준으로 함), 
- NoFeed컴포넌트에서 Link를 Button으로 변경
- 없음
- src/components/NoFeed/NoFeed.jsx
- 없음
close: #124
> feat: Home 페이지 기능 구현

- src/App.jsx
- src/pages/UserSearch/UserSearch.jsx
- src/shared/Header/HeaderSearch.jsx
- src/shared/SimpleUserList/SimpleUserList.jsx
#130
- 없음
- src/App.jsx => "SignUp 페이지 컴포넌트 파일명 및 url import 오류 정정"
- src/pages/UserSearch/UserSearch.jsx
- src/shared/Header/HeaderSearch.jsx
close: #
> feat: search 페이지 구현

- src/components/ModalModule/ModalPostImg.jsx
- src/shared/Post/Post.jsx
#134
- 없음
- src/components/ModalModule/ModalPostImg.jsx
- 없음
close: #134
> fix: Post, ModalPostImg 컴포넌트 이미지 url 수정 작업

- src/pages/Home/Home.jsx
- src/pages/UserSearch/UserSearch.jsx
- src/shared/Post/Post.jsx
- src/shared/SimpleUserList/SimpleUserList.jsx
#135 
- 없음
- src/pages/UserSearch/UserSearch.jsx
- 없음
close: #135
> fix: 사용자 프로필 기본 이미지 설정 및 Home, Search 페이지 디자인 수정 작업

- src/pages/SignUp/SignUp.jsx
- src/shared/Profile/ProfileSetting.jsx
- 없음
- src/shared/Profile/ProfileSetting.jsx
- 없음
이미지를 미리 볼 수 있습니다. 또한 한글을 입력하였을 때 경고메시지를 띄워줍니다.
중복된 계정ID를 사용하였을 경우 경고메시지를 띄워줍니다.
회원가입을 할 때 placehoder를 넣어봤는데 어떤지 코멘트 달아주시면 감사할 것 같습니다.
close: #121
> feat: 회원가입 기능 구현

- src/pages/PostUpload/PostUpload.jsx
- 없음
- src/pages/PostUpload/PostUpload.jsx
- 없음
close: #131
> Feat/포스트 수정 구현

- src/hooks/useIntersect.jsx
- src/pages/Home/Home.jsx
- src/pages/SignUp/SignUp.jsx
- 없음
- src/hooks/useIntersect.jsx
- 없음
close: #
> chore: typo 에러 수정

- src/components/CheckAuth/CheckAuth.jsx
- src/context/UserContext.jsx
#150
- 없음
- src/components/CheckAuth/CheckAuth.jsx
- src/context/UserContext.jsx
close: #150
> feat: ContextAPI를 이용하여 사용자 프로필 정보를 전역으로 접근 가능하도록 하는 기능 구현

- src/shared/Footer/Footer.jsx
#156
- 없음
- src/shared/Footer/Footer.jsx
- 없음
close: #156
> feat: useContext를 이용하여 사용자 계정의 프로필 페이지로 이동하는 기능 구현

- src/index.css
> chore: btn-cancel 오타 수정

- src/pages/SignUp/SignUp.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- src/shared/Profile/ProfileSetting.jsx
- 없음
- src/pages/SplashScreen/SplashScreen.jsx
- src/shared/Profile/ProfileSetting.jsx
close: #140
> feat: token과 userEmail유무에 따른 URL이동

- src/index.css
- src/pages/LoginHome/LoginHome.jsx
- src/pages/SplashScreen/SplashScreen.jsx
- 없음
- src/pages/LoginHome/LoginHome.jsx
- src/pages/SplashScreen/SplashScreen.jsx
화면을 줄여도 레이아웃을 유지합니다.
splashScreen 페이지 레이아웃도 수정하였습니다.
close: #152
> design: splashScreen, LoginHome레이아웃 수정 및 index.css수정

- src/pages/UserFeed/UserFeed.jsx
> feat: club 변수 초기 상태 null 설정에 따른 렌더링 이슈 해결

- src/pages/PostUpload/PostUpload.jsx
- 없음
- src/pages/PostUpload/PostUpload.jsx
- 없음
close: #167
> chore: 화살표 함수 및 오타 수정

- src/pages/ClubUpload/ClubUpload.jsx
- 없음
- src/pages/ClubUpload/ClubUpload.jsx
- 없음
close: #149
> feat: club 게시글 수정 구현 완료 (api 연결 포함, 네비게이트는 수정 필요)

- src/pages/SplashScreen/SplashScreen.jsx
- tailwind.config.js
#design: SplashScreen 애니메이션 효과 추가
- 없음
- src/pages/SplashScreen/SplashScreen.jsx
- tailwind.config.js
- 없음
close: #164
> design: SplashScreen 애니메이션 효과 추가

- src/shared/Profile/UserProfile.jsx
- src/shared/SimpleUserList/SimpleUserList.jsx
- 없음
- 
-  src/shared/SimpleUserList/SimpleUserList.jsx
- 없음
close: #170
> chore: btn-cancel 오타 수정 반영

- src/pages/Follows/Follows.jsx
- src/pages/UserFeed/UserFeed.jsx
- src/shared/Header/HeaderFollow.jsx
- src/shared/Profile/UserProfile.jsx
#161 
- UserFeed 팔로우 api 요청 (팔로우 CRUD) 
- Follows 페이지로의 연결
- Follows의 헤더 구현
- src/pages/Follows/Follows.jsx
- src/shared/Header/HeaderFollow.jsx
- followers 페이지
- followings 페이지
- 사용자 프로필 페이지
- 팔로우 하는 타인 계정의 프로필 페이지
- 팔로우 하는 타인 계정의 프로필 페이지 언팔로우하기
- 팔로우 안된 타인 계정의 프로필 페이지 팔로우하기
close: #161
> feat: UserFeed 팔로우 api 요청 및 Follow 페이지 연결 기능 구현

- src/components/ModalModule/ModalPostImg.jsx
- src/components/SimpleClub/SimpleClub.jsx
- src/pages/ClubUpload/ClubUpload.jsx
- src/pages/PostUpload/PostUpload.jsx
- src/shared/Post/Post.jsx
- src/shared/Post/PostAlbum.jsx
- src/shared/UserClub/UserClub.jsx
> Refactor/issue 195 이미지 경로 및 클럽 업로드 수정

- src/components/ModalModule/ModalPostImg.jsx
- src/pages/UserFeed/UserFeed.jsx
- src/shared/Post/Post.jsx
- src/shared/Post/PostAlbum.jsx
- 게시글 이미지 모달을 앱 화면 안으로 넣었습니다.
- 임의 채팅을 안에 넣어서 디자인 요소를 추가했습니다.
- 임의 채팅 프로필 사진은 게시글 작성자 프로필입니다.
- 없음
- src/components/ModalModule/ModalPostImg.jsx
- 없음
close: #200
> refactor: 모달 포스트 이미지 컴포넌트 이미지 및 기능 리팩토링

- src/components/ModalModule/ModalPoast.jsx
- src/components/ModalModule/ModalPost.jsx
- src/pages/PostDetail/PostChatModal.jsx
- src/pages/PostDetail/PostDetail.jsx
- src/pages/PostUpload/PostUpload.jsx
- src/pages/UserFeed/UserFeed.jsx
- src/shared/Post/Post.jsx
#feat/issue 199 게시글 댓글 페이지 및 모달 추가
- 유저 피드에서 게시글 없거나 로딩시 디자인 추가
- 모달 삭제 버튼 클릭 시 확인창 모달 추가 작업 필요
- 없음
- src/components/ModalModule/ModalPoast.jsx
- src/pages/PostDetail/PostDetail.jsx
- src/pages/PostUpload/PostUpload.jsx
- src/pages/PostDetail/PostChatModal.jsx
- 첫 번째 사진은 지난번에 혼자 머지한 거라 같이 첨부합니다.
close: #199
> feat/issue 199 게시글 댓글 페이지 및 모달 추가

- src/pages/UserFeed/UserFeed.jsx
#146
- 최초 렌더링시 10개의 유저 피드 데이터만 요청
- targetRef 요소가 intersection 되면 getUserFeeds 함수를 통해 유저 피드 데이터 10개 추가 요청
- 없음
- 없음
close: #146
> feat: UserFeed 페이지 유저 피드 데이터 요청(getUserFeeds 함수) useIntersect hook 이용

- src/components/ModalModule/ModalPost.jsx
- src/shared/Post/Post.jsx
#203. #205 
- 없음
- src/components/ModalModule/ModalPost.jsx
- 없음
close: #205
> chore: PR #203 ModalPoast를 ModalPost로 정정

- src/pages/Follows/Follows.jsx
- src/shared/Profile/UserProfile.jsx
- src/shared/SimpleUserList/SimpleUserList.jsx
#207
- UserProfile에서 사용자 팔로우 및 언팔로우 요청에 따른 UserProfile follower, following 렌더링 구현
- 사용자 계정 별 팔로우 및 팔로잉 리스트 데이터 요청
- 요청한 데이터만큼 SimpleUserList 표기
- SimpleUserList 내부 버튼 동작을 통해 팔로우 및 언팔로우 요청 가능
- 없음
- src/pages/Follows/Follows.jsx
- 없음
close: #207
> feat: 팔로우 페이지 구현

- src/components/ModalModule/ModalPost.jsx
- src/pages/PostDetail/PostChatModal.jsx
- src/pages/PostDetail/PostDetailForm.jsx
- src/shared/Post/Post.jsx
- 댓글 입력 시 엔터 중복 업로드 수정했습니다.
- 안 쓰는 변수 및 주석 삭제했습니다.
- 없음
- src/components/ModalModule/ModalPost.jsx
- src/pages/PostDetail/PostChatModal.jsx
- src/pages/PostDetail/PostDetailForm.jsx
- 없음
close: #209
> refactor/issue 209 삭제 모달창에 확인창 추가

- src/pages/UserSearch/UserSearch.jsx
- src/shared/SimpleUserList/SimpleUserList.jsx
#212
- isSearchMode props 추가
- Search 페이지에서 handleLink 이벤트 함수 navigate 수정
- SimpleUserList isSearchMode props 추가
- accountname을 userAccount로 props 명명 수정 
- 없음
- src/pages/UserSearch/UserSearch.jsx
- 없음
close: #212
> fix: SimpleUserList 컴포넌트 handleLink 및 props 에러에 따른 undefined 수정

- src/pages/UserFeed/UserFeed.jsx
> fix: props drilling에 따른 follow, unfollow 비동기 관리 문제 해결

- src/pages/EditProfile/EditProfile.jsx
> fix: url이 부정확한 경우 x-box뜨는 버그 수정

- src/shared/Post/Post.jsx
> feat: 좋아요 기능 구현 완료

- src/pages/SignupProfile/SignupProfile.jsx
- 없음
- src/pages/SignupProfile/SignupProfile.jsx
- 없음
close: #217
> 프로필 이미지 업로드시 기본이미지 baseProfile로 대체

- src/components/ModalModule/Modal.jsx
- 없음
- src/components/ModalModule/Modal.jsx
- 없음
close: #226
> feat: 로그아웃 기능 구현

- src/pages/UserFeed/UserFeed.jsx
> design: UserFeed 게시글이 없는 경우 대체 이미지 및 텍스트 스타일

- src/index.css
- src/shared/Profile/UserProfile.jsx
#234
- UserProfile 레이아웃 및 스타일 조정
- index.css 버튼 높이 레이아웃 height 대신 padding 상하단
- 없음
- 없음
close: #234
> design: UserProfile 레이아웃 및 스타일 조정

- src/components/ModalModule/ModalInfo.jsx
- src/pages/ChatRoom/ChatRoom.jsx
- src/shared/Header/HeaderChat.jsx
- 없음
- src/components/ModalModule/ModalInfo.jsx
- src/pages/ChatRoom/ChatRoom.jsx
- src/shared/Header/HeaderChat.jsx
- 없음
채팅방 나가기 모달이 활성화 된 모습입니다 
클릭시 위와 같이 알림창을 띄워줍니다.
close: #233
> feat: 채팅방 나가기 모달 구현(작동x)

- src/pages/EditProfile/EditProfile.jsx
- src/pages/UserFeed/UserFeed.jsx
- src/shared/Footer/Footer.jsx
- src/shared/Profile/UserProfile.jsx
- 없음
- src/shared/Footer/Footer.jsx
- 없음
close: #239 #174
> fix/issue 239  프로필 수정 및 타 유저에서 내 프로필로 이동시 화면 재렌더링 추가

- src/shared/Profile/UserProfile.jsx
> fix: 프로필 수정 및 모임 만들기 부분에 조건부 렌더링 추가

- src/shared/Profile/UserProfile.jsx
> feat: 공유하기 url 복사 기능 구현

- src/shared/UserClub/UserClub.jsx
- 없음
- src/shared/UserClub/UserClub.jsx
- 없음
close: #247
> refactor: UserClub의 버튼 색상 변경

- src/shared/Profile/UserProfile.jsx
> design: 프로필 이미지에 cover 속성 추가

- src/App.jsx
- src/components/SimpleClub/SimpleClub.jsx
- src/pages/ClubUpload/ClubUpload.jsx
- src/pages/UserFeed/UserFeed.jsx
- src/shared/UserClub/UserClub.jsx
- src/shared/UserClub/UserClubModal.jsx
- 유저가 다른 경우 명세서에 신고하기는 없지만 신고 버튼을 넣어 alert 처리만 넣어줬습니다.
- 수정 기능 추가에 따른 라우팅 수정
- 유저 피드에서 UserClub으로 prorps 전달 (isUpload를 통한 삭제 재렌더링)
-  없음
- src/App.jsx
- src/components/SimpleClub/SimpleClub.jsx
- src/pages/ClubUpload/ClubUpload.jsx
- src/shared/UserClub/UserClubModal.jsx
close: #253
> feat/issue 253 feat/issue 253 UserClub 페이지 구현 (수정/삭제)

- src/pages/UserSearch/UserSearch.jsx
#263
- 없음
- src/pages/UserSearch/UserSearch.jsx
- 없음
- 성능상에 유의미한 차이가 있는지 불분명합니다.
- 추가적인 개선이 요구됩니다.
close: #
> fix: setTimeout을 설정하여 findUser 함수 동작 딜레이 적용

- src/components/CheckAuth/CheckAuth.jsx
- src/shared/Footer/Footer.jsx
- src/shared/Profile/UserProfile.jsx
- 없음
- src/components/CheckAuth/CheckAuth.jsx
- src/shared/Footer/Footer.jsx
- 없음
- 
close: #267
> fix: 프로필 계정 이름 변경 시 화면 렌더링 오류 해결

- public/404.html
- public/index.html
- public/index.html
- public/404.html
close: #
> build: git hub pages에 spa 적용하기

- src/pages/UserFeed/UserFeed.jsx
- src/shared/UserClub/UserClubModal.jsx
- 없음
- 
- src/shared/UserClub/UserClubModal.jsx
- 
- 없음
close: #278
> fix: 모임 소개 콤마 오류 및 게시글 삭제 렌더링 리베이스

- src/shared/UserClub/UserClubModal.jsx
- 없음
- src/shared/UserClub/UserClubModal.jsx
- 없음
close: #
> chore: 이미지에 cover 속성 추가

- src/pages/UserFeed/UserFeed.jsx
- src/shared/UserClub/UserClubModal.jsx
- 없음
- src/shared/UserClub/UserClubModal.jsx
- 없음
close: #
> build : 이미지 cover 속성 추가

- src/test/LoginHome.test.jsx
- 없음
- 없음
- src/test/LoginHome.test.jsx
close: #298
> test: LoginHome 컴포넌트 테스트 코드 추가

- src/pages/LoginHome/LoginHome.jsx
- 없음
- src/pages/LoginHome/LoginHome.jsx
- 없음
close: #302
> test: LoginHome Link 요소 구체화를 위한 role 속성 추가

- src/pages/EditProfile/EditProfile.jsx
- src/pages/LoginEmail/LoginEmail.jsx
- src/pages/SignUp/SignUp.jsx
- src/pages/SignupProfile/SignupProfile.jsx
#306
-
- src/pages/LoginEmail/LoginEmail.jsx
- src/pages/SignupProfile/SignupProfile.jsx
-
close: #306
> refactor: btnColor, btnDisabled 제거 및 isActive로 통합관리

- src/pages/SignUp/SignUp.jsx
#320 
- Signup 컴포넌트 리펙토링
1. emailRef, passwordRef를inputRef로 통합관리
2. 사용자 email, password 입력값을 formData로 통합관리
3. email과 password의 문자열 길이가 일정 조건을 만족하면 버튼을 활성화 시킴
4. 만일 활성화된 이후 다시 활성조건을 만족하지 못하게 되면 비활성화 되도록 함
-
- 
close: #320
> refactor: Signup 컴포넌트 리펙토링

- src/pages/LoginEmail/LoginEmail.jsx
#328
-
- src/pages/LoginEmail/LoginEmail.jsx
-
close: #328
> refactor: LoginEmail 컴포넌트 입력값 리팩토링

- src/pages/EditProfile/EditProfile.jsx
> refactor: EditProfile 컴포넌트 입력 리팩토링

- src/hooks/useLengthCheck.jsx
#338
-
-
- src/hooks/useLengthCheck.jsx
close: #338
> feat: useLengthCheck 커스텀 훅 생성

- src/pages/EditProfile/EditProfile.jsx
- src/pages/LoginEmail/LoginEmail.jsx
- src/pages/SignUp/SignUp.jsx
- src/pages/SignupProfile/SignupProfile.jsx
#340
-
- src/pages/LoginEmail/LoginEmail.jsx
- src/pages/SignupProfile/SignupProfile.jsx
-
close: #340
> refactor: useLengthCheck 적용

- src/index.css
- src/pages/Home/Home.jsx
> deploy: index.css 수정사항 반영
